### PR TITLE
FR-3647 Upgrade to latest starship version and copy cert file

### PR DESCRIPTION
**Pull request by audax-shreyaspurohit**
@danstaley @KyleMessner @gmazza @sportanova @joshx0rfz @macmacbr 

I will be releasing and deploying this version on dev7 after merge.

### CODE REVIEW

**Comment by joshx0rfz** [comment]
lgtm

**Comment by rallyhealthangel** [comment]
lgtm

**Comment by KyleMessner** [comment]
lgtm

**Comment by gmazza** [comment]
lgtm with a comment:  LGTM!

**Pull request merged**
