### PR TITLE
Move access-manager out of SE repo

### PR DESCRIPTION
**Pull request by audax-shreyaspurohit**
@danstaley @gmazza @KyleMessner @sportanova @joshx0rfz @rjaguilar @rallyhealthangel @macmacbr 

This PR moves access manger to a separate repo maintaining all history. Please note that any new PR to web/accessmanager and web/ui/accessmanager must be done here too till I move Jenkins to use this repo. I have tested this locally and the play app runs fine using this on local. 

The only caveat is, you must run below command before running play app using this repo. This config is set in backend project and is common across for all dependencies and obviously there is no web/base in this repo. I will change this to a generic path for the local deployment in SE repo soon in a PR.

```
export STARSHIP_AUTHN_PUBLICCERTPATH=/code/StarshipEnterprise/web/base/test/com/rallyhealth/starship/controller/dev-cert.crt
```

This is the only commit that I modified for fixing build system for this repo: https://github.com/AudaxHealthInc/starship-accessmanager/commit/de9c7b0fffbaab84a260e1aa43660985dfa26c4c 
 
#### Things to do:
1. ~~Jenkin setup & github hooks~~
2. move dev-cert.crt path to /etc/careverge or add /code/SE in backend default for local deployments (any other suggestions welcome)

### CODE REVIEW

**Comment by audax-shreyaspurohit** [comment]
Jenkins Build Success: http://jenkins.infra.careverge.com:8080/job/Build_Starship_AccessManager/3/console

**Comment by gmazza** [comment]
lgtm

**Comment by KyleMessner** [comment]
speaking with Dan, would it be possible to just copy the cert @audax-shreyaspurohit ? I think that might be easier for now until everything is moved out to vault.

**Comment by KyleMessner** [comment]
LGTM

**Comment by danstaley** [comment]
+1 on just copying the cert to this service.  We will eventually be changing these all over to pulling the cert from Vault anyway.  @PainterAndHacker is working on the initial vault implementation as we speak:  https://github.com/AudaxHealthInc/lib-secrets/pull/2

**Comment by danstaley** [comment]
LGTM

**Comment by audax-shreyaspurohit** [comment]
copying cert will do. I will move it to web/cert/dev-cert.crt so that path is common across all service repo's.

**Pull request merged**
